// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw5mfkmycOC9O_s54pSX7P5x7kqDMDKr8',
    appId: '1:179684321700:web:0a0a6878303c54dc48b931',
    messagingSenderId: '179684321700',
    projectId: 'fluttercrud-f7e2a',
    authDomain: 'fluttercrud-f7e2a.firebaseapp.com',
    storageBucket: 'fluttercrud-f7e2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnZADdTvbaMxLmocbvqaqiJ9lwR87z30',
    appId: '1:179684321700:android:c406e5369e7ccbed48b931',
    messagingSenderId: '179684321700',
    projectId: 'fluttercrud-f7e2a',
    storageBucket: 'fluttercrud-f7e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMFLxzlINGdfti_V4CEvwop4mj8lmI4OI',
    appId: '1:179684321700:ios:6a82c3a53e082cb148b931',
    messagingSenderId: '179684321700',
    projectId: 'fluttercrud-f7e2a',
    storageBucket: 'fluttercrud-f7e2a.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMFLxzlINGdfti_V4CEvwop4mj8lmI4OI',
    appId: '1:179684321700:ios:6a82c3a53e082cb148b931',
    messagingSenderId: '179684321700',
    projectId: 'fluttercrud-f7e2a',
    storageBucket: 'fluttercrud-f7e2a.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw5mfkmycOC9O_s54pSX7P5x7kqDMDKr8',
    appId: '1:179684321700:web:8fc893b1106609cd48b931',
    messagingSenderId: '179684321700',
    projectId: 'fluttercrud-f7e2a',
    authDomain: 'fluttercrud-f7e2a.firebaseapp.com',
    storageBucket: 'fluttercrud-f7e2a.appspot.com',
  );
}
